- index.ts
This PR adds comprehensive JSDoc documentation to the codebase while preserving the original Korean comments.
- Added proper JSDoc comments to all functions
- Preserved original Korean comments
- Added Korean translations for English-only functions
- No functional code changes - documentation only
This documentation will make the codebase more maintainable and accessible to both Korean and English-speaking developers.
> Improve code documentation with bilingual JSDoc comments

- build/index.js
- build/schemas.js
- index.ts
- schemas.ts
> Add schemas for GitLab discussion notes and merge request discussions

- index.ts
- package-lock.json
- package.json
I need to access the gitlab api through socks, this PR supports this functionality
> feat: Implement proxy configuration for HTTP/HTTPS/SOCKS

- README.md
- index.ts
- package.json
- schemas.ts
This MR introduces a new feature that allows users to ask questions about pipeline status and summaries.
1. Example 1 : _"How many of the last N pipelines are green (successful)?"_
2. Example 2: _"Can you make a summary of the output in the last pipeline using a bulleted list?"_
👍
> feat(release): 1.0.44  adds pipeline jobs tool

- schemas.ts
https://github.com/zereight/gitlab-mcp/issues/57
> fix(schemas): make illustration nullable in GitLabPipelineSchema

- README.md
- scripts/image_push.sh
https://github.com/zereight/gitlab-mcp/issues/54
> FEAT: docker image push script

- index.ts
- schemas.ts
I've added tools for milestones. Although I'm only using some of them in my workflow, I've just implemented all of the following:
- list_milestones
- get_milestone
- create_milestone
- edit_milestone
- delete_milestone
- get_milestone_issue
- get_milestone_merge_requests
- promote_milestone
- get_milestone_burndown_events
> feat: add tools for milestones

- README.md
📝 Details:
- Added comments for USE_GITLAB_WIKI and USE_MILESTONE options for clarity.
> [main] docs: update README with comments on GITLAB configuration options

- index.ts
- schemas.ts
https://github.com/zereight/gitlab-mcp/issues/74#issuecomment-2934906620
> FIX: bug get issues

- index.ts
- package-lock.json
> FEAT: private token auth

- index.ts
> FIX: private token auth

- README.md
> FIX: sse readme

- index.ts
simple healthcheck endpoint to make working worth the mcp server over longer time periods easier.
feel free to suggest any changes needed.
> feat(simple healthcheck):

- README.md
- index.ts
issue: #110 111
https://github.com/zereight/gitlab-mcp/issues/110
https://github.com/zereight/gitlab-mcp/issues/111
> FEAT: project id , vscode doc

- index.ts
> FIX: create pipeline

- index.ts
> FIX: default project id

- package-lock.json
- package.json
> chore: Bump version to 1.0.70

- index.ts
- schemas.ts
> FIX: string | number for gemini

- index.ts
- schemas.ts
- utils.ts
> FEAT: enable string for boolean for claude

- package.json
@iwakitakuma33 Tag v1.0.72 added
> chore: Bump version 1.0.72

- customSchemas.ts
- schemas.ts
> FIX: id string or number

- customSchemas.ts
- index.ts
- schemas.ts
https://github.com/zereight/gitlab-mcp/issues/153
https://github.com/zereight/gitlab-mcp/issues/157
> FIX string or number

- index.ts
> FEAT: add logging

- index.ts
- schemas.ts
> FEAT: target project on create MR

- schemas.ts
> FEAT: issue type on update list create issue

- index.ts
- schemas.ts
> FEAT: get draft note

- index.ts
- schemas.ts
> FEAT: merge MR

- .github/workflows/npm-publish.yml
I created an npm workflow. Like docker yml.
And I added secret to the repo. like this
The DOCKERHUB_USERNAME is `zeregith050`.
I'd like to check it success.
> feat: Add NPM publish workflow

- Dockerfile
Add `EXPOSE` with default port on DockerFile
> Add `EXPOSE`  on Dockerfile
