zereight/gitlab-mcp

- index.ts
Added the missing api/v4 part to the URL, and changed merge_request to merge_requests according to https://docs.gitlab.com/api/notes/
> Added missing api url part to create_note

- index.ts
This pull request fixes two issues in the createNote function:
1. Uses plural form for resource types (issues, merge_requests) in the URL path
2. Removes duplicate /api/v4 in URL construction, which caused 404 errors
These changes align with the GitLab API documentation and fix 404 errors when adding notes to issues or merge requests.
The fix has been tested and confirmed to work with both numeric project IDs and project path formats, and for both issues and merge requests.
> Fix createNote function URL construction: use plural resource names and avoid duplicate /api/v4

- build/index.js
- index.ts
- package.json
- test-note.ts
This PR fixes the issues described in #9.\n\nChanges in this PR:\n\n1. Added a robust normalizeGitLabApiUrl function to handle various URL formats\n2. Normalizing API URLs to have /api/v4 exactly once\n3. Ensuring all URL constructions use consistent paths\n4. Added version reading from package.json\n\nThis supersedes PR #7 with a more comprehensive fix including proper version handling from package.json. The fix has been tested with both numeric project IDs and path formats for issues and merge requests.
> Fix URL construction with smart API URL normalization

- index.ts
- schemas.ts
This PR addresses issues reported in #12 by fixing the parameter handling in the fork_repository function.
- Made the owner property optional in GitLabForkParentSchema
- Made the forked_from_project property optional in GitLabForkSchema
- Improved error handling in the fork_repository MCP handler
Resolves #12
Manually tested and verified that the fork_repository function now works correctly with the GitLab API, even when optional fields are missing from the response.
> Fix GitLab API fork repository parameter handling

- index.ts
- schemas.ts
This PR adds support for the GitLab Namespaces API as documented at https://docs.gitlab.com/api/namespaces/
Features:
- Added schemas for namespaces and API responses
- Implemented three namespace-related functions:
- list_namespaces: List all available namespaces with filtering
- get_namespace: Get details about a specific namespace
- verify_namespace: Check if a namespace exists
These functions are useful for workflows that need to manage projects across different namespaces.
> Add GitLab Namespaces API support

- index.ts
- schemas.ts
This PR adds support for the GitLab Projects API as documented at https://docs.gitlab.com/api/projects/
Features:
- Enhanced GitLabRepositorySchema with additional project fields
- Added comprehensive GET and LIST operations for projects
- Implemented two project-related functions:
- get_project: Get details on a specified project
- list_projects: List projects accessible by the current user
These functions are useful for AI assistants that need to:
- List and filter available projects
- Get detailed information about specific projects
- Access project metadata for GitLab operations
This PR builds on top of the Namespaces API support (#15)
> Add GitLab Projects API support

- README.md
- index.ts
- schemas.ts
This PR adds support for the GitLab Labels API:
- Implements functions for managing project labels (list, get, create, update, delete)
- Adds ability to create, update, and delete labels
- Includes proper error handling and parameter validation
- Fixes authentication method in the listProjects function to use DEFAULT_HEADERS consistently
The PR adds the following endpoints:
1. `list_labels`: List all labels for a project with filtering options
2. `get_label`: Get a single label from a project
3. `create_label`: Create a new label in a project
4. `update_label`: Update an existing label in a project
5. `delete_label`: Delete a label from a project
- Updated the `GitLabLabelSchema` to properly handle all fields returned by the GitLab API
- Added schemas for all label operations:
- …
> Labels API Support

- index.ts
This PR addresses an issue with authentication header usage in the GitLab MCP server:
- Ensures consistent use of DEFAULT_HEADERS across all API calls
- Refactors the list_projects function to use a properly implemented helper function
- Improves maintainability by removing duplicate code
The PR focuses on ensuring that all API calls use the predefined DEFAULT_HEADERS constant, which contains the proper authentication headers for GitLab API requests. Specifically:
- The `list_projects` handler has been refactored to use the existing `listProjects` helper function
- This eliminates duplicate code and ensures consistent authentication header usage
- The implementation follows the pattern used by other API functions in the codebase
The changes have been tested against a GitLab instance and …
> Authentication Header Consistency Fix

- README.md
- index.ts
- package-lock.json
Adds GITLAB_READ_ONLY_MODE environment variable that restricts server operations to read-only tools when enabled. This enhances security for sensitive GitLab instances and helps stay within Cursor's 40 tool limit.
Changes:
- Add GITLAB_READ_ONLY_MODE environment variable support
- Filter available tools to read-only operations when enabled
- Update documentation in README.md
- Consolidate Cursor and Claude App configuration sections
> feat: Add read-only mode support

- index.ts
- package-lock.json
- schemas.ts
Allow for searching merge request by branch id based on this REST API query
`GET /projects/:project_id/merge_requests?source_branch=:source_branch&state=opened`
Added additional optional parameter `source_branch` to `get_merge_request` parameter.
> feat: support search by branch for get_merge_request

- index.ts
- package-lock.json
- schemas.ts
This PR adds a `list_repository_tree` tool for the Gitlab MCP, so AI agents can explore repositories interactively.
Originally created this [PR inside the official gitlab integration](https://github.com/modelcontextprotocol/servers/pull/1337), but they are not the fastest so I have decided to submit it here as well. 
This PR adds a `list_repository_tree` tool for the Gitlab MCP, so It can explore a repository interactively. It wraps around the corresponding [List repository tree](https://docs.gitlab.com/api/repositories/#list-repository-tree).
The AI agents are in the dark regarding the structure of a repository and can only read specific files in their entirety. This PR adds the `list_repository_tree` to allow the AI to explore the repository before reading/updating specific files.
See …
> feat: Gitlab list repository tree tool

- index.ts
- package-lock.json
- schemas.ts
Allow the ability to resolve/unresolve notes in merge request discussions through the MCP API. Basically, the Gitlab API expects either `body` or `resolved`, but not both. The existing code here required `body` to be provided. I simply made that field optional.
Here is a reference to where this is called out in the API docs: https://docs.gitlab.com/api/discussions/#modify-an-existing-merge-request-thread-note
> Support resolving merge request discussion notes

- README.md
- index.ts
- schemas.ts
Adds two new MCP tools to improve the comment experience on merge requests. These changes allow threads to be created with inline code suggestions and notes to be added to existing threads.
1. `create_merge_request_thread` - Start new threads on merge requests, with support for diff notes and comment positioning
2. `create_merge_request_note` - Reply to existing threads
`create_note` as is does not support this functionality, so figured I would extend to support these two new tools instead.
> Adds threaded comment support for merge requests

- Dockerfile
- README.md
- package-lock.json
Hi,
I build a standard docker image to run the mcp server and pushed to my public Dockerhub repo.
Happy to change to yours once it pushed by you.
Thanks!
> feat: add docker image and push to dockerhub

- README.md
- index.ts
- schemas.ts
Added `list_issue_discussions` tool to support GitLab issue discussions similar to merge request discussions.
> feat: add issue discussions support

- README.md
- index.ts
- schemas.ts
- Added create_issue_note to add a new note to an existing issue thread
- Added update_issue_note to modify an existing issue thread note
- Similar to existing merge request note functions but for issues
> feat: add support for creating and updating issue notes

- schemas.ts
@zereight 
I apologize if the MR writing format or branch name violates the rules.
Thank you for the invitation.
[Issue](https://github.com/zereight/gitlab-mcp/issues/51):
The MCP server fails to process GitLab issues that contain a null value for the description field. This causes the server to throw a JSON-RPC error instead of returning issue details.
Error Message:
```
{
"jsonrpc": "2.0",
"id": 8,
"error": {
"code": -32603,
"message": "Invalid arguments: description: Expected string, received null"
}
}
```
> FIX: description null error

- schemas.ts
Users without profile pictures have null avatar_url values in GitLab API responses. This change prevents errors when calling get_issue tool.
> fix(schemas): make avatar_url nullable in GitLabUserSchema

- .github/workflows/pr-test.yml
- Fix startup_failure errors in PR validation workflow
- Remove unsupported default value syntax from secrets
GitHub Actions doesn't support the `||` operator for providing default values in secret expressions like:
```yaml
${{ secrets.GITLAB_API_URL || 'https://gitlab.com' }}
```
This causes a startup_failure error and prevents the workflow from running.
Removed all default value expressions from secrets. The workflow now uses only:
```yaml
${{ secrets.GITLAB_API_URL }}
```
After merging this PR, other PRs will be able to run the automated tests properly.
> Fix GitHub Actions workflow syntax errors

- README.md
- index.ts
- schemas.ts
- test/validate-api.js
This PR adds pipeline management commands to address #46.
- `create_pipeline` - Create a new pipeline for a branch or tag
- `retry_pipeline` - Retry a failed or canceled pipeline  
- `cancel_pipeline` - Cancel a running pipeline
- Added pipeline management schemas in `schemas.ts`
- Implemented pipeline functions in `index.ts`
- Added pipeline API tests in `test/validate-api.js`
- Updated README with new pipeline commands
- All existing tests pass
- Added new pipeline API validation tests
- Tested list_pipelines and get_pipeline endpoints
Closes #46
> feat: add pipeline management commands

- index.ts
- schemas.ts
According to GitLab's API documentation (https://docs.gitlab.com/api/wikis/#list-wiki-pages), the response of the wiki pages API only includes the content field when the `with_content` parameter is set to true.
Changes made:
- Added optional `with_content` parameter to ListWikiPagesSchema
- Made the content field optional in GitLabWikiPageSchema to properly handle responses with and without content
- Updated the listWikiPages function to support the new parameter
- Updated the request handler to pass the parameter to the API
> fix: current list_wiki_pages tool is not working and add support for retrieving wiki page content in list_wiki_pages

- .env.example
- .github/workflows/pr-test.yml
- README.md
- index.ts
- package-lock.json
- package.json
- scripts/load_env.sh
- test/clients/client.ts
- test/clients/sse-client.ts
- test/clients/stdio-client.ts
- test/clients/streamable-http-client.ts
- test/test-all-transport-server.ts
- test/utils/server-launcher.ts
Add modern Streamable HTTP transport protocol support to GitLab MCP server, fully compatible with the previous version. At the same time, test clients for STDIO, SSE, and Streamable HTTP transport protocols were developed, and relevant test cases for MCP services were constructed based on them..
```bash
STREAMABLE_HTTP=true  # Enable streamable-http transport
```
- Fully backward compatible with existing stdio and SSE transport modes
- Defaults to stdio mode when environment variables are not set
- Maintains all existing APIs and configurations unchanged
- Added comprehensive test suite for all three transport modes
- Covers connection, tool invocation, and session management core functionalities
- Tests transport priority selection logic
- Added streamable-http configuration examples in …
> FEAT: Add support for Streamable HTTP transport

- index.ts
Commit 3ad2954 inadvertently sent log messages to stdout instead of stderr. This breaks the stdio transport.
> Print logs to stderr

- src/gitlabhandler.ts
- src/mcpserver.ts
- src/schemas.ts
Added functionality for working with GitLab tags API, including listing, retrieving, creating, deleting tags, and getting tag signatures.
> feat(tags): Implement GitLab tags API functionality

- README.md
- index.ts
This will help in certain cases by reducing the number of tools to lower the context length of the LLM.
> FEAT: add GITLAB_DENIED_TOOLS_REGEX env to disable some tools
